pipeline {
  agent none

  environment {
    docker_label="nljenkinsagent"
    nlw_host="nlweb.shared"
    api_url="http://${env.nlw_host}:8080"
    zone_id="defaultzone"
  }

  stages {
    stage ('Prep workspace') {
      agent any
      steps {
        cleanWs()
        script {
          sh "uname -a"
          env.host_ip = sh(script: "getent hosts ${env.nlw_host} | head -n1 | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])'", returnStdout: true)
          env.agent_name = "${env.VM_HOST_EXT_IP}" // sh(script: "uname -a | tr -s ' ' | cut -d ' ' -f2", returnStdout: true)
        }
      }
    }
    stage('Attach Worker') {
      agent {
        docker {
          image "${env.docker_label}:latest"
          args "--add-host ${env.nlw_host}:${env.host_ip} -e HOME=${env.WORKSPACE} -e PYTHONUNBUFFERED=1"
        }
      }
      stages {
        stage('Prepare agent') {
          steps {
            sh 'neoload --version'
            withCredentials([string(credentialsId: 'NLW_TOKEN', variable: 'NLW_TOKEN')]) {
              sh "neoload login --url ${env.api_url} $NLW_TOKEN"
            }
          }
        }
        stage('Prepare Neoload test') {
          steps {
            sh "neoload test-settings --zone ${env.zone_id} --lgs 1 --scenario sanityScenario createorpatch 'example-Jenkins-module3-${env.agent_name}'"
            sh "neoload project --path tests/neoload_projects/example_1/ upload"
            sh "neoload status"
          }
        }
        stage('Run Test') {
          steps {
            sh """neoload run \
              --detached \
              --name \"${env.JOB_NAME}-${env.BUILD_NUMBER}-${env.agent_name}\" \
              --as-code default.yaml,slas/uat.yaml
             """

            sh 'echo "Detached Exit Code was: $?"'

            script {
              logs_url = sh(script: "neoload logs-url cur", returnStdout: true).trim()
              echo "Logs url: ${logs_url}"

              try {
                sh "neoload fastfail --max-failure 25 slas cur"
              } finally {
                exitCode = sh(script: "neoload wait cur", returnStatus: true)
                print "Final status code was ${exitCode}"
              }
            }
          }
          post {
              always {
                sh "neoload test-results junitsla"
                junit testResults: 'junit-sla.xml', allowEmptyResults: true
              }
          }
        }
      }
    }
  }
}
